name: lint test build
run-name: ${{ github.actor }} run pipelines 🚀
on:
  pull_request:
    types: [opened, edited, reopened]
    branches:
      - master
  push:
    branches:
      - master
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: "Подключаемся к репозиторию"
        uses: actions/checkout@v3
      - name: "Кэшируем модули"
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: "устанавливаем node_modules"
        run: npm ci
      - name: "прогоняем линт TS"
        run: npm run lint-ts
      - name: "прогоняем линт SCSS"
        run: npm run lint-css
  build:
    needs: [linting]
    continue-on-error: true
    strategy:
      matrix:
        node-version: [ 17.x ]
    runs-on: ubuntu-latest
    steps:
      - name: "Подключаемся к репозиторию"
        uses: actions/checkout@v3
      - name: "Запускаем node.js версии ${{ matrix.node-version }}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "устанавливаем node_modules"
        run: npm ci
      - name: "собираем build"
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: build
  deploy:
    needs: [ linting ]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: "Подключаемся к репозиторию"
        uses: actions/checkout@v3
      - name: "Достаем модули из кеша (закешированы в job:linting)"
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: "устанавливаем node_modules"
        run: npm ci
      - name: "собираем build"
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: build

